apiVersion: v1
kind: Service
metadata:
  name: android-cicd-dashboard-service

spec:
  selector:
    app: android-cicd-dashboard

  ports:
  - port: 80
    targetPort: 80
    nodePort: 30081

  type: NodePort
